apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: togglemaster
  labels:
    app: evaluation-service
    app.kubernetes.io/part-of: togglemaster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: 889629667863.dkr.ecr.us-east-1.amazonaws.com/togglemaster/evaluation-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8004
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          env:
            - name: PORT
              value: "8004"
            - name: FLAG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: FLAG_SERVICE_URL
            - name: TARGETING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: TARGETING_SERVICE_URL
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: AWS_REGION
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: evaluation-service-secret
                  key: REDIS_URL
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: evaluation-service-secret
                  key: SERVICE_API_KEY
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: evaluation-service-secret
                  key: SQS_QUEUE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
