apiVersion: v1
kind: ConfigMap
metadata:
  name: togglemaster-config
  namespace: togglemaster
data:
  SERVICE_API_KEY_NAME: "internal-service-key"
  AUTH_SERVICE_URL: "http://auth-service.togglemaster.svc.cluster.local:8001"
  FLAG_SERVICE_URL: "http://flag-service.togglemaster.svc.cluster.local:8002"
  TARGETING_SERVICE_URL: "http://targeting-service.togglemaster.svc.cluster.local:8003"
  EVALUATION_SERVICE_URL: "http://evaluation-service.togglemaster.svc.cluster.local:8004"
  AWS_REGION: "us-east-1"
  SQS_QUEUE_NAME: "ToggleMasterEvents"
  DYNAMODB_TABLE_NAME: "ToggleMasterAnalytics"
