apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:ToggleMaster123@togglemaster-db-auth.c.us-east-1.rds.amazonaws.com:5432/authdb?sslmode=disable"
  MASTER_KEY: "admin-master-key-togglemaster"
  SERVICE_API_KEY: "tm_key_super_secret_internal_token_auth"
---
apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:ToggleMaster123@togglemaster-db-flag.c.us-east-1.rds.amazonaws.com:5432/flagdb"
  SERVICE_API_KEY: "tm_key_super_secret_internal_token_flag"
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:ToggleMaster123@togglemaster-db-targeting.c.us-east-1.rds.amazonaws.com:5432/targetingdb"
  SERVICE_API_KEY: "tm_key_super_secret_internal_token_targeting"
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  REDIS_URL: "redis://togglemaster-cache.c.us-east-1.cache.amazonaws.com:6379"
  SERVICE_API_KEY: "tm_key_super_secret_internal_token_eval"
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/889629667863/ToggleMasterEvents"
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/889629667863/ToggleMasterEvents"
  DYNAMODB_TABLE: "ToggleMasterAnalytics"
