apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: togglemaster
  labels:
    app: analytics-service
    app.kubernetes.io/part-of: togglemaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: 889629667863.dkr.ecr.us-east-1.amazonaws.com/togglemaster/analytics-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8005
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          env:
            - name: PORT
              value: "8005"
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: AWS_REGION
            - name: AWS_SQS_URL
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secret
                  key: SQS_QUEUE_URL
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secret
                  key: SQS_QUEUE_URL
            - name: AWS_DYNAMODB_TABLE
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secret
                  key: DYNAMODB_TABLE
            - name: DYNAMODB_TABLE
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secret
                  key: DYNAMODB_TABLE
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
